name: myGamePipe

on: [push]

jobs:
  btp:
    runs-on: ubuntu-latest
    name: btp
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn compile
      - name: Run tests with Maven
        run: mvn test
      - name: Create Package
        run: mvn package
      - name: upload build
        uses: actions/upload-artifact@v3
        with: 
          name: compiled-files
          path: target/*.war
  
  deploy:
    runs-on: self-hosted
    needs: btp
    steps:
      - name: get-artifact
        uses: actions/download-artifact@v3
        with: 
          name: compiled-files
      
            
    
        
        

      
